### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by vladinator1000** [HriBB/apollo-upload-network-interface#11]
Hi guys, is there a complete working example of the implementation of this somewhere? I've never done file uploads before. I'm a bit stuck and don't know where to start. I've been having trouble getting stuff to work: http://stackoverflow.com/questions/42058634/upload-image-to-graphql-server

**Comment by savovs** [comment]
The instructions here are marvelous: https://github.com/HriBB/graphql-server-express-upload
