### ISSUE TITLE
GraphQL error: Variable "image" not used

### ISSUE THREAD

**Issue by srosset81** [HriBB/apollo-upload-network-interface#9]
I'm trying to upload a file like this:

```js
const ATTACH_IMAGE = gql`
  mutation attachImage($entityID: Int!, $mappingName: String!, $image: UploadedFile) {
    attachImage(entityID:$entityID, mappingName:$mappingName) {
      __typename
      id
      url
    }
}`;

this.props.client.mutate({
   mutation: ATTACH_IMAGE,
   variables: {
      image: this.state.uploadedFile,
      entityID: 3,
      mappingName: "organization_background"
   }
```

But I get this error message: 

```
GraphQL error: Variable "image" not used
```

It seems that Apollo checks the mutation and notices that the $image variable is not used anywhere, even though I need to set it if I want the apollo-upload-network-interface to take care of it. I already had this problem when I did a custom implementation of a network interface, and the only way I found is to manually remove the `$image: UploadedFile` bit from the mutation string, not a great solution!

Any idea of what might go wrong? Do you have a working example somewhere?

**Comment by HriBB** [comment]
Hey @srosset81, I think it has something to do with #3. Try passing `FileList` instead of a single `File`. I will try to fix this after NY, but ATM I have no time to do this.

**Comment by srosset81** [comment]
Thanks, I'll look into this.
Have a good holidays!

Le 23 déc. 2016 16:06, "Bojan Hribernik" <notifications@github.com> a
écrit :

**Comment by srosset81** [comment]
Hello,

Actually just removing `$image: UploadedFile` from the query solved this problem.
As for handling File in addition to FileList, it is quite simple:

On the isUpload() function:

```
if (request.variables[key] instanceof FileList || request.variables[key] instanceof File) {
    return true
}
```

and on the getUploadOptions() function:

```
        for (let key in request.variables) {
            let v = request.variables[key]
            if (v instanceof FileList) {
                Array.from(v).forEach(f => body.append(key, f))
            } else if (v instanceof File) {
                body.append(key, v);
            } else {
                variables[key] = v
            }
        }
```
